services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mstudio\ContaoExhibitorsBundle\:
        resource: '../src/'
        exclude:
            - '../src/ContaoExhibitorsBundle.php'
            - '../src/ContaoManager/'
            - '../src/Model/'
